// Extra catalog items (beyond the official price sheet), added with photos.
// They have NO fixed price — shop staff set the price when they add the item
// to an order (in the POS "Add item" panel, or at intake). priceForItem() will
// return null for these, and the UI shows "\u2014" until a price is entered.
export type ExtraItem = { key: string; en: string; ar: string; categoryKey: string; image?: string };

export const EXTRA_ITEMS: ExtraItem[] = [
  { key: "daraa_special_2", en: "Daraa special 2", ar: "دراعة خاصة ٢", categoryKey: "women", image: "/items/daraa_special_2.jpg" },
  { key: "bathrobe", en: "Bathrobe", ar: "روب حمام", categoryKey: "household", image: "/items/bathrobe.jpg" },
  { key: "daraa", en: "Daraa", ar: "دراعة", categoryKey: "women", image: "/items/daraa.jpg" },
  { key: "gilet", en: "Gilet / Vest", ar: "جيليه / صديري", categoryKey: "men", image: "/items/gilet.jpg" },
  { key: "tracksuit_trouser", en: "Tracksuit Trouser/Pants", ar: "بنطلون تراكسوت", categoryKey: "men", image: "/items/tracksuit_trouser.jpg" },
  { key: "leather_shoes", en: "Leather shoes", ar: "حذاء جلد", categoryKey: "cleaning", image: "/items/leather_shoes.jpg" },
  { key: "blanket_special", en: "Blanket special", ar: "بطانية خاصة", categoryKey: "household", image: "/items/blanket_special.jpg" },
  { key: "bra", en: "Bra", ar: "حمالة صدر", categoryKey: "women", image: "/items/bra.jpg" },
  { key: "child_fancy_dress", en: "Children Fancy Dress", ar: "فستان أطفال فاخر", categoryKey: "children", image: "/items/child_fancy_dress.jpg" },
  { key: "child_dishdasha", en: "Children Dishdasha", ar: "دشداشة أطفال", categoryKey: "children", image: "/items/child_dishdasha.jpg" },
  { key: "pillow_special_small", en: "Pillow Special Small", ar: "مخدة خاصة صغيرة", categoryKey: "household", image: "/items/pillow_special_small.jpg" },
  { key: "jean_jacket", en: "Jean jacket", ar: "جاكيت جينز", categoryKey: "men", image: "/items/jean_jacket.jpg" },
  { key: "child_shorts", en: "Children Shorts", ar: "شورت أطفال", categoryKey: "children", image: "/items/child_shorts.jpg" },
  { key: "pyjamas", en: "Pyjamas", ar: "بيجاما", categoryKey: "men", image: "/items/pyjamas.jpg" },
  { key: "boiler_suit", en: "Boiler Suit / Coveralls", ar: "أفرول / بدلة عمل", categoryKey: "men", image: "/items/boiler_suit.jpg" },
  { key: "duvet_special", en: "Duvet Special", ar: "لحاف خاص", categoryKey: "household", image: "/items/duvet_special.jpg" },
  { key: "blanket_children", en: "Blanket (Children)", ar: "بطانية أطفال", categoryKey: "children", image: "/items/blanket_children.jpg" },
  { key: "tracksuit_jacket", en: "Tracksuit Jacket", ar: "جاكيت رياضي", categoryKey: "men", image: "/items/tracksuit_jacket.jpg" },
  { key: "child_sweater", en: "Children Sweater / Pullover", ar: "كنزة أطفال", categoryKey: "children", image: "/items/child_sweater.jpg" },
  { key: "fancy_tshirt", en: "Fancy t-shirt", ar: "تي شرت فاخر", categoryKey: "men", image: "/items/fancy_tshirt.jpg" },
  { key: "fancy_dress", en: "Fancy Dress", ar: "فستان فاخر", categoryKey: "women", image: "/items/fancy_dress.jpg" },
  { key: "long_shirt", en: "Long shirt", ar: "قميص طويل", categoryKey: "men", image: "/items/long_shirt.jpg" },
  { key: "silk_nightgown", en: "Silk Nightgown", ar: "قميص نوم حرير", categoryKey: "women", image: "/items/silk_nightgown.jpg" },
  { key: "vest", en: "Vest", ar: "صديري", categoryKey: "men", image: "/items/vest.jpg" },
  { key: "bath_towel_large", en: "Bath Towel (Large)", ar: "منشفة حمام (كبير)", categoryKey: "household", image: "/items/bath_towel_large.jpg" },
  { key: "shoes_trainer", en: "Shoes trainer / sneakers", ar: "حذاء رياضي", categoryKey: "cleaning", image: "/items/shoes_trainer.jpg" },
  { key: "duvet_children", en: "Duvet (Children)", ar: "لحاف أطفال", categoryKey: "children", image: "/items/duvet_children.jpg" },
  { key: "party_dress", en: "Party Dress", ar: "فستان حفلة", categoryKey: "women", image: "/items/party_dress.jpg" },
  { key: "sofa_cover_large", en: "Sofa Cover (Large)", ar: "غطاء كنبة (كبير)", categoryKey: "household", image: "/items/sofa_cover_large.jpg" },
  { key: "toys", en: "Toy's", ar: "ألعاب", categoryKey: "children", image: "/items/toys.jpg" },
  { key: "shawl", en: "Shawl", ar: "شال", categoryKey: "women", image: "/items/shawl.jpg" },
  { key: "dress_pleated", en: "Dress Pleated", ar: "فستان بليسيه", categoryKey: "women", image: "/items/dress_pleated.jpg" },
  { key: "tablecloth_ornate", en: "Tablecloth Ornate (Per Meter)", ar: "مفرش طاولة مزخرف (بالمتر)", categoryKey: "household", image: "/items/tablecloth_ornate.jpg" },
  { key: "child_shirt", en: "Children Shirt", ar: "قميص أطفال", categoryKey: "children", image: "/items/child_shirt.jpg" },
  { key: "officer_cap", en: "Officer Uniform Cap", ar: "كاب زي رسمي", categoryKey: "men", image: "/items/officer_cap.jpg" },
  { key: "school_uniform", en: "School uniform", ar: "زي مدرسي", categoryKey: "children", image: "/items/school_uniform.jpg" },
  { key: "besht", en: "Besht", ar: "بشت", categoryKey: "men", image: "/items/besht.jpg" },
  { key: "child_gutra", en: "Children Gutra", ar: "غترة أطفال", categoryKey: "children", image: "/items/child_gutra.jpg" },
  { key: "saree", en: "Saree", ar: "ساري", categoryKey: "women", image: "/items/saree.jpg" },
  { key: "doctors_coat", en: "Doctors coat", ar: "بالطو طبيب", categoryKey: "men", image: "/items/doctors_coat.jpg" },
  { key: "ihram", en: "Ihram clothes", ar: "ملابس إحرام", categoryKey: "men", image: "/items/ihram.jpg" },
  { key: "dungaree", en: "Dungaree / Overall (jeans)", ar: "أفرول جينز", categoryKey: "men", image: "/items/dungaree.jpg" },
  { key: "tablecloth_normal", en: "Tablecloth Normal (Per Meter)", ar: "مفرش طاولة عادي (بالمتر)", categoryKey: "household", image: "/items/tablecloth_normal.jpg" },
  { key: "hand_towel", en: "Hand towel", ar: "منشفة يد", categoryKey: "household", image: "/items/hand_towel.jpg" },
  { key: "child_skirt", en: "Children Skirt", ar: "تنورة أطفال", categoryKey: "children", image: "/items/child_skirt.jpg" },
  { key: "officer_trouser", en: "Officer Uniform Trouser/Pants", ar: "بنطلون زي رسمي", categoryKey: "men", image: "/items/officer_trouser.jpg" },
  { key: "officer_shirt", en: "Officer Uniform Shirt", ar: "قميص زي رسمي", categoryKey: "men", image: "/items/officer_shirt.jpg" },
  { key: "besht_winter", en: "Besht (Winter)", ar: "بشت شتوي", categoryKey: "men", image: "/items/besht_winter.jpg" },
  { key: "niqab", en: "Niqab", ar: "نقاب", categoryKey: "women", image: "/items/niqab.jpg" },
  { key: "dress_special", en: "Dress Special", ar: "فستان خاص", categoryKey: "women", image: "/items/dress_special.jpg" },
];
